"""Level 1 Schema Migration

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2025-08-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # Create nutrient_profiles table
    op.create_table('nutrient_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile_name', sa.String(length=255), nullable=False),
        sa.Column('target_tds_ppm_min', sa.Integer(), nullable=True),
        sa.Column('target_tds_ppm_max', sa.Integer(), nullable=True),
        sa.Column('nutrient_focus', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('profile_name')
    )

    # Create sensor_readings table
    op.create_table('sensor_readings',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('farm_id', sa.Integer(), nullable=False),
        sa.Column('location_id', sa.String(length=50), nullable=True),
        sa.Column('metric_code', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('status', sa.String(length=50), server_default='normal', nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add columns to crops table
    op.add_column('crops', sa.Column('ideal_temp_min_celsius', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('crops', sa.Column('ideal_temp_max_celsius', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('crops', sa.Column('ideal_light_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('crops', sa.Column('nft_suitability_notes', sa.Text(), nullable=True))
    op.add_column('crops', sa.Column('nutrient_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_nutrient_profile', 'crops', 'nutrient_profiles', ['nutrient_profile_id'], ['id'])

    # Add columns to farms table
    op.add_column('farms', sa.Column('unit_system', sa.String(length=20), server_default='metric', nullable=False))
    op.add_column('farms', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    op.add_column('farms', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))

    # Add column to users table
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # Drop column from users table
    op.drop_column('users', 'language')

    # Drop columns from farms table
    op.drop_column('farms', 'currency')
    op.drop_column('farms', 'timezone')
    op.drop_column('farms', 'unit_system')

    # Drop columns and foreign key from crops table
    op.drop_constraint('fk_nutrient_profile', 'crops', type_='foreignkey')
    op.drop_column('crops', 'nutrient_profile_id')
    op.drop_column('crops', 'nft_suitability_notes')
    op.drop_column('crops', 'ideal_light_hours_per_day')
    op.drop_column('crops', 'ideal_temp_max_celsius')
    op.drop_column('crops', 'ideal_temp_min_celsius')

    # Drop tables
    op.drop_table('sensor_readings')
    op.drop_table('nutrient_profiles')
    # ### end Alembic commands ###
